CI impl 2

diff --git a/.github/actions/prepare-ee-test-env/action.yml b/.github/actions/prepare-ee-test-env/action.yml
--- a/.github/actions/prepare-ee-test-env/action.yml
+++ b/.github/actions/prepare-ee-test-env/action.yml
@@ -16,11 +16,6 @@ inputs:
   sdk-download-token:
     required: true
     type: string
-  skip-etcd-install:
-    description: Whether to skip etcd installation
-    type: boolean
-    required: false
-    default: false
 
 env:
   # Note: Use exactly match version of tool, to avoid unexpected issues with test on CI.
@@ -39,19 +34,6 @@ runs:
       with:
         python-version: '${{ env.PYTHON_VERSION }}'
 
-    - name: Setup Mage
-      run: |
-        git clone https://github.com/magefile/mage
-        cd mage
-        go run bootstrap.go
-      shell: bash
-
-    - name: Install build requirements
-      run: |
-        sudo apt -y update
-        sudo apt -y install git gcc make cmake unzip zip fish zsh
-      shell: bash
-
     - name: Cache Tarantool SDK
       id: cache-sdk
       uses: actions/cache@v3
@@ -64,9 +46,20 @@ runs:
         ARCHIVE_NAME=tarantool-enterprise-sdk-${{ inputs.sdk-gc }}-${{ inputs.sdk-version }}.tar.gz
         ARCHIVE_PATH=$(echo ${{ inputs.sdk-version }} | sed -rn \
           's/^([0-9]+)\.([0-9]+)\.([0-9]+-){2}([a-z0-9]+-)?r[0-9]+\.([a-z]+)\.([a-z0-9_]+)$/${{ inputs.sdk-build }}\/\5\/\6\/\1\.\2/p')
-        curl -O -L -v \
-          https://tarantool:${{ inputs.sdk-download-token }}@download.tarantool.io/enterprise/${ARCHIVE_PATH}/${ARCHIVE_NAME}
-        tar -xzf ${ARCHIVE_NAME}
-        rm -f ${ARCHIVE_NAME}
-        source tarantool-enterprise/env.sh
+          curl -O -L \
+            https://${{ inputs.sdk-download-token }}@download.tarantool.io/enterprise/${ARCHIVE_PATH}/${ARCHIVE_NAME}
+          if [ $(stat -c%s "${ARCHIVE_NAME}") -eq 0 ]; then
+            echo "Failed to download Tarantool EE SDK: '${ARCHIVE_PATH}/${ARCHIVE_NAME}'"
+            exit 1
+          fi
+          tar -xzf ${ARCHIVE_NAME}
+          rm -f ${ARCHIVE_NAME}
+          source tarantool-enterprise/env.sh
+      shell: bash
+
+    - name: Add SDK to PATH and set TARANTOOL_SDK_PATH variable
+      run: |
+        SDK_PATH="$(realpath tarantool-enterprise)"
+        echo "${SDK_PATH}" >> ${GITHUB_PATH}
+        echo "TARANTOOL_SDK_PATH=${SDK_PATH}" >> ${GITHUB_ENV}
       shell: bash
